apiVersion: apps/v1
kind: Deployment
metadata:
  name: daniyalRepo
  labels:
    app: daniyalRepo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daniyalRepo
  template:
    metadata:
      labels:
        app: daniyalRepo
    spec:
      containers:
        - name: daniyalRepo
          image: 489994096722.dkr.ecr.us-east-1.amazonaws.com/daniyal-repo:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080