apiVersion: apps/v1
kind: Deployment
metadata:
  name: primuslearning
  labels:
    app: primuslearning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primuslearning
  template:
    metadata:
      labels:
        app: primuslearning
    spec:
      containers:
        - name: daniyal-repo
          image: 489994096722.dkr.ecr.us-east-1.amazonaws.com/daniyal-repo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080