apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: github-runner-api
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: github-runner-api-sa
      automountServiceAccountToken: true
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true
      labels:
        - k8s-api
      repository: prjmpkcopper/k8s-runner-test
      workVolumeClaimTemplate:
        storageClassName: "standard"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      env: []