name: Auto Build/Deploy

on:
  push:
    branches:
      - "*"

jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: self-hosted
    steps:
      - name: Start EC2 runner
        run: pwd
  do-the-job:
    name: Do the job on the runner
    runs-on: self-hosted
    needs: start-runner # required to start the main job when the runner is ready
    steps:
      - name: Hello World
        run: pwd
  stop-runner:
    name: Stop self-hosted EC2 runner
    runs-on: self-hosted
    needs:
      - start-runner # required to get output from the start-runner job
      - do-the-job # required to wait when the main job is done
    steps:
      - name: Hello World
        run: pwd
  
          