name: Auto Build/Deploy

on:
  push:
    branches:
      - "*"

jobs:
  start-runner:
    name: Start kubernetes runner
    runs-on: self-hosted
    steps:
      - name: Start kubernetes runner
        run: pwd
  do-the-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

  run-npm-test:
    runs-on: self-hosted
    needs: do-the-job
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, and test
        run: |
          touch package.json
          npm install
          npm test
        env:
          CI: true

  stop-runner:
    name: Stop runner
    runs-on: self-hosted
    needs:
      - start-runner # required to get output from the start-runner job
      - do-the-job # required to wait when the main job is done
    steps:
      - name: Hello World
        run: pwd
  
          