name: Auto Build/Deploy

on:
  push:
    branches:
      - "*"

jobs:
  start-runner:
    name: Start kubernetes runner
    runs-on: self-hosted
    steps:
      - name: Start kubernetes runner
        run: pwd
  do-the-job:
    name: Do the job on the runner
    runs-on: self-hosted
    needs: start-runner # required to start the main job when the runner is ready
    strategy: 
        matrix:
            node-version: [12.x]
    steps:
      - uses: actions/checkout@v3

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: app1
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: app2

      - name: App1 tests
        run: npm t
        working-directory: app1
      - name: Run app2
        run: node .
        working-directory: app2
  stop-runner:
    name: Stop runner
    runs-on: self-hosted
    needs:
      - start-runner # required to get output from the start-runner job
      - do-the-job # required to wait when the main job is done
    steps:
      - name: Hello World
        run: pwd
  
          