name: Auto Build/Deploy

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build
    runs-on:
      - self-hosted
    steps:
      - name: Get Pods
        run: |
          set -ex
          cd $HOME
          pwd
          ls -la
